### PR TITLE
MantaClient Making Extra HTTP Request For Encrypted Objects (#217)

### PR DESCRIPTION
**Pull request by uxcn**
This eliminates an extra http (head) request for encrypted byte ranges.

### CODE REVIEW

**Comment by uxcn** [comment]
The mockito mocks for stuff don't seem to be being init'd in travis ci for some reason.  I will look into this as soon as I can.

**Comment by uxcn** [comment]
Since this is a fairly large pull request, it probably makes sense to go into a bit more detail.  This pull request eliminates an http head request to a manta server for encrypted object byte ranges, essentially implementing a formal byte range api.

Currently, encrypted byte range requests (relative) require initial round trip tcp bytes from the client to the server, before any actual byte request, to fix offsets that are dependent on the object size (e.g. account for block size and mac); essentially making the request twice.  This unfortunately adds to the request latency, as well as making the request non-atomic (request more likely to fail).

It unfortunately leaves a couple things unaddressed, which were previously unaddressed (e.g. a closed byte range request that accidentally, or possibly intentionally, requests plaintext bytes that are part of the ciphertext mac [not currently tested]).  Prior code assumes no invalid requests, which I think might result in a negative file offset.

The integration tests pass in us-east an on a local machine, but seem to be failing in travis-ci.  I can't determine why, but the testng `@BeforeSuite` annotation doesn't seem to be being parsed.

**Comment by tjcelaya** [comment]
@uxcn Could you explain the algorithm for determining explicit byte ranges based on implicit ranges a bit more? How would we be able to calculate the end of the range if we don't know how big the object is? Your formulas mentioned in #217 neglect to explain the way some of the values are defined, but `request_end_pos` depends on the object size and would need to make the same HEAD request.

```
manta_end_pos = request_end_pos - (block_size - (request_end_pos % block_size)) - mac_auth_bytes (padded cipher)

manta_end_pos = request_end_pos - mac_auth_bytes (non-padded cipher)
```

Quoting your last comment:
> Currently, encrypted byte range requests (relative) require initial round trip tcp bytes from the client to the server, before any actual byte request, to fix offsets that are dependent on the object size (e.g. account for block size and mac); essentially making the request twice.

While there are two requests occurring it is an overgeneralization to say "making the request twice" since the `HEAD` request only contains metadata needed to perform the second request correctly. The block comment above the line you referenced which issues the HEAD request mentions this fact: https://github.com/joyent/java-manta/blob/master/java-manta-client/src/main/java/com/joyent/manta/http/EncryptionHttpHelper.java#L370

Running the integration test suite with `mvn verify` on your branch causes every `MantaClientRangeIT` test to fail with the following exception thrown from your code:

```
(com.joyent.manta.client.MantaClientRangeIT)  Time elapsed: 0.651 sec  <<< FAILURE!
com.joyent.manta.exception.MantaException: incorrect separator, should be ' ' (range=bytes 827-892/893)
	at com.joyent.manta.http.MantaHttpHeaders.getContentRange(MantaHttpHeaders.java:1208)
	at com.joyent.manta.http.EncryptionHttpHelper.httpRequestAsInputStream(EncryptionHttpHelper.java:558)
	at com.joyent.manta.client.MantaClient.getAsInputStream(MantaClient.java:407)
	at com.joyent.manta.client.MantaClientRangeIT.canGetWithUnboundedStartRange(MantaClientRangeIT.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:147)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
```

**Comment by uxcn** [comment]
> Could you explain the algorithm for determining explicit byte ranges based on implicit ranges a bit more? How would we be able to calculate the end of the range if we don't know how big the object is? Your formulas mentioned in #217 neglect to explain the way some of the values are defined, but request_end_pos depends on the object size and would need to make the same HEAD request.

The values submitted to the server are entirely dependent on properties of the ciphers.  There are still issues (even in the current implementation) when values requested eat into the `mac`, but those can be caught in the response (assuming manta is rfc-7233 compliant'ish).

> While there are two requests occurring it is an overgeneralization to say "making the request twice" since the HEAD request only contains metadata needed to perform the second request correctly. The block comment near the line you link to explains why the request needs to happen:

The major issue, which might or might not be a problem for users, is that an initial `head` request is another http/network request, which eats into an application request response budget.

For example, assuming a (reasonably generous) 300ms budget for a response...

    <application request> => <head request (t ms)> => <head response (v ms)> => <get request (t ms)> => <application response>

If *t* is ~150ms, the application misses its deadline (user interactivity in this case).  Sans `head` request, there's a fairly roomy 150ms to spare.

It's (hopefully) a less common use case, but the additional request still eats into the user's application response time budget.

In all sincerity, my two big concerns with this pull request were usability and security, which is why I took as extreme caution as I did to identify the potential errors and security flaws (including possible user errors), and move as much possible to compile time (hopefully saving some grief).

**Comment by uxcn** [comment]
> Finally, running the integration test suite with mvn verify on your branch causes every MantaClientRangeIT test to fail with the following exception thrown from your code:

Looking at the exception, the `Content-Range` value doesn't look like it matches the [rfc-7233](https://tools.ietf.org/html/rfc7233) examples although I might be wrong (slightly late).

**Pull request closed without merging**
