### PR TITLE
Fixes #61

### LINKED ISSUE #61: MantaClient should interpret JSON content for manta errors and build structured exceptions
Currently, various MantaClient methods throw MantaClientHttpResponseException which does not provide a sufficient interface which applications can use to understand the underlying error.  The manta service sends back JSON content describing the error, but the manta client builds the exception based on the http-oriented semantics (http status code) rather than the manta-oriented semantics (manta service error code).

Applications ARE able to access the JSON that manta sends back, but it's up to the application to parse the JSON and interpret the error content.

### PR DESCRIPTION
**Pull request by dekobon**
Adds error response enum. Parses JSON error response from Manta API.

### CODE REVIEW

**Comment by dekobon** [comment]
@phillipross Please review when you have a free moment.

**Comment by phillipross** [comment]
The code looks good, but for some reason, when I've checked out the branches the last few times to browse the code within the IDE, the tests don't seem to run.  I wasn't sure if you had temporarily disabled these while you were working on getting the CI up and running or if this was a mistake or something.  I think there might be a little more work necessary for the test suite wiring.

Also... the CI doesn't seem to be checking the checkstyle rules.  Is that on purpose as well?

**Comment by phillipross** [comment]
Oops, I think I see what the problem is with the testsuite.  I can fix it but I'm not sure what your intentions were with how the CI runs which test suites and when.  I would assume the we'd want the CI to be able to invoke a build with and without style checks and tests suite checks... and this should be able to be driven with -D system properties on the maven invocation.  Is that correct?

**Comment by dekobon** [comment]
@phillipross, 3f0d373dc3b9dc568e85c3c5208945fbff9986f0 should resolve the issues with tests and style checks running in CI. As for your IDE, I'm not sure what the problem is. Could it be that I added some dependsOn annotations to TestNG? All of the tests are running on my side. I'm going to go ahead and merge.

**Comment by phillipross** [comment]
I have no problems specifically with the IDE, I was just referring to the process of reviewing the PRs by looking at the diffs rendered by github versus checking out the code into my IDE and reviewing it in the IDE editor.

The checkstyle problem seems to stem from the fact that the default property value for checkstyle is set to skip the checkstyle checks: `<checkstyle.skip>true</checkstyle.skip> `

The travis config does not seem to explicitly override this.  It needs `-Dcheckstyle.skip=false`

Also, I dont think the `-DskipITs=true` is doing anything.  The integration tests don't run due to some maven configuration.  I'm actually traveling at the moment, but I'll be back at my desk tomorrow and can provide more info on the maven config.  Thanks!

**Comment by dekobon** [comment]
In the .travis.yml, I specified:

```yaml
language: java
sudo: false

before_install:
  - echo 'MAVEN_OPTS="-Dorg.slf4j.simpleLogger.defaultLogLevel=warn"' >~/.mavenrc

matrix:
  fast_finish: true
  include:
    # checkstyle
    - jdk: oraclejdk8
      env:
        - DESC="checkstyle"
        - CMD="mvn clean checkstyle:checkstyle -Dcheckstyle.skip=false"
    # unit tests (oraclejdk8)
    - jdk: oraclejdk8
      env:
        - DESC="oraclejdk8 unit tests"
        - CMD="mvn clean verify -DskipITs=true"

script: echo ${CMD}; ${CMD}
```
Do you think that this is broken somehow?

**Comment by phillipross** [comment]
Woops, I didn't see the dedicated checkstyle rule there.
I see it now, and it looks correct, but I know the build was passing even when there were checkstyle errors.  I'll take a closer look at the current state though.

**Comment by phillipross** [comment]
I see now... the checkstyle invocation as you have it does not work, but if you change it to use the validate phase which is how the checkstyle plugin is bound into the build, it should work:
`mvn clean validate -Dcheckstyle.skip=false`

I'm not immediately certain why it doesn't work when invoking the checkstyle plugin directly, but I can look into it if you want.

**Comment by phillipross** [comment]
Hah, ok ok... the `checkstyle` goal is a reporting goal for generating reports.  The `check` goal is the one for immediately running checkstyle.  The `check` goal is the one that is bound to the `validate` phase.

**Comment by phillipross** [comment]
I'm about to submit a PR that will refactor the maven configs for testing to enable the integration tests execution.  I'll include changes to the travis config file to modify the checkstyle rule (I want to test travis behavior with PRs) so you may see some weird initial commits on the PR.  Please don't try to merge the PR before I get the real changes in :grinning:  thanks!

**Comment by dekobon** [comment]
Ok. Sounds great!

On Mon, Nov 23, 2015 at 2:38 PM, Phillip Ross <notifications@github.com>
wrote:

> I'm about to submit a PR that will refactor the maven configs for testing
> to enable the integration tests execution. I'll include changes to the
> travis config file to modify the checkstyle rule (I want to test travis
> behavior with PRs) so you may see some weird initial commits on the PR.
> Please don't try to merge the PR before I get the real changes in [image:
> :grinning:] thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joyent/java-manta/pull/75#issuecomment-159090095>.
>



-- 
-Elijah

**Pull request merged**
