### PR TITLE
bug fixes

### PR DESCRIPTION
**Pull request by phillipross**
Fixed https://github.com/joyent/java-manta/issues/39
Fixed https://github.com/joyent/java-manta/issues/49
Fixed https://github.com/joyent/java-manta/issues/51

### CODE REVIEW

**Comment by phillipross** [comment]
@dekobon please review when you get time.

**Comment by dekobon** [comment]
Looks great.

**Comment by dekobon** [comment]
I didn't catch it before I merged. Can you add the bugs fixed to the changelog?

**Comment by phillipross** [comment]
I'll need some guidance with this.  Copy and paste github URLs for the issues that are resolved into the changelog file?

**Comment by dekobon** [comment]
Yes, I'm thinking we will do something like:

```
### Fixed
 - [README specifies incorrect system property name for manta user](https://github.com/joyent/java-manta/issues/48)
```

**Pull request merged**
