### PR TITLE
Fix Integration Test Path Prefixes

### PR DESCRIPTION
**Pull request by tjcelaya**
See #319

Still need to verify this actually fixes all possible object paths.

### CODE REVIEW

**Comment by tjcelaya** [comment]
The branch name references the wrong issue but this PR is still useful, reopened.

**Comment by cburroughs** [comment]
This fixes #319 specifically by guaranteeing that the test prefix ends in a slash? (So that the sloppy joining via string concatenation works?)

**Comment by cburroughs** [comment]
I think this looks reasonable, could you answer the above question just make sure I understand?

**Comment by tjcelaya** [comment]
Yes that's the plan. I revisited this branch today and realized the trailing slash was missing. Running `watch ~~/stor/java-manta-integration-tests/` alongside an `mvn verify` to make sure the tests clean up after themselves.

Additionally updated `TESTING.md` to show how the new integration test path setting could be used for #320.

**Comment by tjcelaya** [comment]
I can confirm an empty `~~/stor/java-manta-integration-test/` folder after completion of the verify phase. This PR is ready to merge.

**Pull request merged**
