### PR TITLE
Fix #295

### LINKED ISSUE #295: Network error triggers retry on standard PUT causes file corruption
Terminating a standard PUT request will trigger a retry without resetting encryption state. Moving EncryptionContext instantiation to `writeTo`

### PR DESCRIPTION
**Pull request by tjcelaya**
See #295

### CODE REVIEW

**Comment by tjcelaya** [comment]
This won't work if the encryption IV is added to the header, might need to switch to using `EncryptionStateRecorder`

**Comment by tjcelaya** [comment]
Resolved without resorting to `EncryptionStateRecording`. The new constructor for `EncryptionContext` can be made package-private if desired.

**Comment by tjcelaya** [comment]
Need another test case for ensuring that 503s are handled correctly.

**Comment by cburroughs** [comment]
Could you please add some prose explaining the approach you took? I'm having trouble understanding what looks like a minimum of `EncryptionContext` objects per PUT and why the IV must be preserved (instead of just generating a new one on each try).

**Comment by tjcelaya** [comment]
Sure, the reason for copying over values in `EncryptionContext` is because the IV for each `EncryptingEntity` is generated when the entity constructor builds a `new EncryptionContext`. The IV generated at the time of construction is then attached as a header to the request on [this line](https://github.com/joyent/java-manta/blob/master/java-manta-client/src/main/java/com/joyent/manta/http/EncryptionHttpHelper.java#L212).

I believe this is what opened us up to this bug in the first place. The first commit on this PR naively constructed a new EncryptionContext at the beginning of `writeTo` but the test case would still fail because the objects did not encrypt the same way.

**Comment by cburroughs** [comment]
When an `EncryptingEntity` is constructed, a `EncryptionContext` is created and the cipher is initialized.  On each `writeTo` (including the first) a  `EncryptionContext` is created and new cipher initialed.  Do I have that right?

 * Having a minimum of two cipher initializations doesn't feel right.  Is there any case where the `EncryptionContext` created in the constructor would actually be used?  Maybe `EncryptionContext` could be cleaner if it kept track of the IV and had some sort of reinitialize method.
 * Is the key part preserving the IV, or also the new cipher instance from `cipherDetails.getBouncyCastleCipher()`?

**Comment by tjcelaya** [comment]
> Having a minimum of two cipher initializations doesn't feel right. Is there any case where the EncryptionContext created in the constructor would actually be used? Maybe EncryptionContext could be cleaner if it kept track of the IV and had some sort of reinitialize method.

The `EncryptionContext` needs to be initialized in the constructor since the embedded `Cipher` is used when preparing the headers and the `EncryptionContext` is referenced in `getContentLength`.

> Is the key part preserving the IV, or also the new cipher instance from cipherDetails.getBouncyCastleCipher()?

Primarily the IV. Reinitializing the `Cipher` should work, though I needed to make `EncryptionContext#initializeCipher` package-private so that we can call it from `EncryptingEntity`

**Comment by tjcelaya** [comment]
Calling `initializeCipher` directly works for CTR and CBC but not for GCM. The following exception is thrown:

```
com.joyent.manta.exception.MantaClientEncryptionException: There was a problem loading private key
Exception Context:
	[1:mantaSdkVersion=3.0.0-SNAPSHOT]
	[2:key_details=key=AES, algorithm=RAW]
---------------------------------

	at com.joyent.manta.client.crypto.EncryptionContext.initializeCipher(EncryptionContext.java:120)
	at com.joyent.manta.client.crypto.EncryptingEntity.writeTo(EncryptingEntity.java:142)
	at com.joyent.manta.client.crypto.EncryptingEntityTest.verifyEncryptionWorksRoundTrip(EncryptingEntityTest.java:199)
	at com.joyent.manta.client.crypto.EncryptingEntityTest.canEncryptAndDecryptToAndFromFileWithManySizes(EncryptingEntityTest.java:159)
	at com.joyent.manta.client.crypto.EncryptingEntityTest.canEncryptAndDecryptToAndFromFileWithManySizesInAesGcm(EncryptingEntityTest.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
Caused by: org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher$InvalidKeyOrParametersException: cannot reuse nonce for GCM encryption
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineInit(Unknown Source)
	at javax.crypto.Cipher.init(Cipher.java:1394)
	at javax.crypto.Cipher.init(Cipher.java:1327)
	at com.joyent.manta.client.crypto.EncryptionContext.initializeCipher(EncryptionContext.java:118)
	... 27 more
Caused by: java.lang.IllegalArgumentException: cannot reuse nonce for GCM encryption
	at org.bouncycastle.crypto.modes.GCMBlockCipher.init(Unknown Source)
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher$AEADGenericBlockCipher.init(Unknown Source)
	... 31 more
```

**Comment by cburroughs** [comment]
Thanks for looking.  Given those constraints I'm not sure there is a way that will look more straightforward to the next person who looks at it.  I'd suggest trying to  capture this conversation in comments (ie why we still need the cipher in the constructor).  The javadoc description of `EncryptionContext` may also be misleading now that we are passing copies around instead of the one value object.

**Pull request merged**
