### PR TITLE
adjust mimetype checks to reduce platform specifc behavior

### PR DESCRIPTION
**Pull request by cburroughs**
ref #276

### CODE REVIEW

**Comment by dekobon** [comment]
This is a sensible change. The logic behind the original ordering was that `Files.probeContentType()` was a more accurate detector of mime types than a filename. However, when implemented the platform specific peculiarities weren't taken into account. Both choices are compromises. The correct answer is that the user brings their own mime-type.

**Comment by tjcelaya** [comment]
Since the issue seems to stem from `Files.probeContentType(Path)` being platform-specific, I'm inclined to ask: would it be too much of a breaking change to stop using it entirely? We're already altering functionality with this change by favoring the more consistent detection method, it seems like an opportunity to drop the inconsistent method entirely and have more predictable behavior.

**Comment by dekobon** [comment]
If we drop the mimetype autodetect out of the SDK, we will need to implement it upstack in each library that implements the SDK, like VFS and the Hadoop FS driver. That's ok and arguably we should do it there. I look at this feature as useful fluff. It is nice to see the correct mimetype appear in Manta when you have dragged a file into a box in a third-party component.

**Comment by dekobon** [comment]
Let's merge!

**Comment by dekobon** [comment]
Dang, I just remembered that we didn't update the changelog. Can you do that?

**Pull request merged**
