### PR TITLE
Test suite bugfixes and documentation updates

### PR DESCRIPTION
**Pull request by phillipross**
Fixes remaining artifact of prior merge and addresses issue #20

### CODE REVIEW

**Comment by dekobon** [comment]
Merged in b843850dd414733da27e5501d974115ace867590

**Comment by phillipross** [comment]
Hi @dekobon, did you mean to close this without merging?  This PR actually contains a commit beyond the merge of b843850 which fixes the name mismatches for the parameters passed into a test method.  It also updates the README.md to mention the environment variables overrides of the parameters.

**Comment by dekobon** [comment]
Thanks for letting me know. I thought this was the same PR that I merged before and for some reason it was hanging open.

**Comment by phillipross** [comment]
This PR is still not ready for merging.  There is still an issue an issue with how the configuration parameters are being built.  And when there is a mismatch with the key and the fingerprint, it results in a class cast exception rather than a key validation error.  The tests still fail with the following stack trace when environment variables are not set explicitly to point to the key and corresponding fingerprint
```
java.lang.ClassCastException: org.bouncycastle.openssl.PEMEncryptedKeyPair cannot be cast to org.bouncycastle.openssl.PEMKeyPair
	at com.joyent.manta.client.crypto.HttpSigner.getKeyPair(HttpSigner.java:148)
	at com.joyent.manta.client.crypto.HttpSigner.<init>(HttpSigner.java:105)
	at com.joyent.manta.client.crypto.HttpSigner.newInstance(HttpSigner.java:63)
	at com.joyent.manta.client.MantaClient.<init>(MantaClient.java:177)
	at com.joyent.manta.client.MantaClient.newInstance(MantaClient.java:115)
	at com.joyent.manta.client.MantaClient.newInstance(MantaClient.java:91)
	at com.joyent.manta.client.MantaClient.newInstance(MantaClient.java:68)
	at com.joyent.manta.client.MantaClientTest.beforeClass(MantaClientTest.java:58)
```

**Comment by dekobon** [comment]
In order to repro, I should clear out the env vars and only configure with
the TestNG suite?

On Sun, Nov 1, 2015 at 2:02 PM, Phillip Ross <notifications@github.com>
wrote:

> This PR is still not ready for merging. There is still an issue an issue
> with how the configuration parameters are being built. And when there is a
> mismatch with the key and the fingerprint, it results in a class cast
> exception rather than a key validation error. The tests still fail with the
> following stack trace when environment variables are not set explicitly to
> point to the key and corresponding fingerprint
>
> java.lang.ClassCastException: org.bouncycastle.openssl.PEMEncryptedKeyPair cannot be cast to org.bouncycastle.openssl.PEMKeyPair
>     at com.joyent.manta.client.crypto.HttpSigner.getKeyPair(HttpSigner.java:148)
>     at com.joyent.manta.client.crypto.HttpSigner.<init>(HttpSigner.java:105)
>     at com.joyent.manta.client.crypto.HttpSigner.newInstance(HttpSigner.java:63)
>     at com.joyent.manta.client.MantaClient.<init>(MantaClient.java:177)
>     at com.joyent.manta.client.MantaClient.newInstance(MantaClient.java:115)
>     at com.joyent.manta.client.MantaClient.newInstance(MantaClient.java:91)
>     at com.joyent.manta.client.MantaClient.newInstance(MantaClient.java:68)
>     at com.joyent.manta.client.MantaClientTest.beforeClass(MantaClientTest.java:58)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joyent/java-manta/pull/21#issuecomment-152868872>.
>



-- 
-Elijah

**Comment by phillipross** [comment]
Correct, you still need to define MANTA_USER as that no longer exists in the testng.xml file, but the other environment variables should be cleared out to reproduce the error.

**Pull request closed without merging**
