### PR TITLE
Testing jenkins build

### PR DESCRIPTION
**Pull request by tjcelaya**

### CODE REVIEW

**Comment by cburroughs** [comment]
I'm seeing some  messages in the logs along the lines of:

```
Nov 14, 2017 6:14:59 PM org.jenkinsci.plugins.ghprb.GhprbRepository commentOnFailure
INFO: Could not update commit status of the Pull Request on GitHub.
org.kohsuke.github.HttpException: Server returned HTTP response code: 201, message: 'Created' for URL: https://api.github.com/repos/
joyent/java-manta/statuses/f9ccb3b5ef7f2995cbd3ace5f3e3b6cb1b778881
        at org.kohsuke.github.Requester.parse(Requester.java:633)
        at org.kohsuke.github.Requester.parse(Requester.java:594)
        at org.kohsuke.github.Requester._to(Requester.java:272)
        at org.kohsuke.github.Requester.to(Requester.java:234)
        at org.kohsuke.github.GHRepository.createCommitStatus(GHRepository.java:1071)
        at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.onBuildTriggered(GhprbSimpleStatus.java:144)
        at org.jenkinsci.plugins.ghprb.GhprbBuilds.build(GhprbBuilds.java:74)
        at org.jenkinsci.plugins.ghprb.GhprbPullRequest.build(GhprbPullRequest.java:481)
        at org.jenkinsci.plugins.ghprb.GhprbPullRequest.tryBuild(GhprbPullRequest.java:474)
        at org.jenkinsci.plugins.ghprb.GhprbPullRequest.check(GhprbPullRequest.java:166)
        at org.jenkinsci.plugins.ghprb.GhprbRepository.check(GhprbRepository.java:172)
        at org.jenkinsci.plugins.ghprb.GhprbRepository.check(GhprbRepository.java:152)
        at org.jenkinsci.plugins.ghprb.GhprbTrigger.run(GhprbTrigger.java:313)
        at hudson.triggers.Trigger.checkTriggers(Trigger.java:278)
        at hudson.triggers.Trigger$Cron.doRun(Trigger.java:226)
        at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
        at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

Which sounds sort of like: https://github.com/jenkinsci/ghprb-plugin/issues/579

I take it builds do not appear to be working?

**Comment by tjcelaya** [comment]
Thanks for checking it out, looks like the build is passing now. Did anything get updated?

**Comment by cburroughs** [comment]
I didn't upgrade.  It looks like from the ticket chain (JENKINS-47601)  that an upgrade of relevant plugins should fix the issue.  I can do that this evening or tomorrow when builds are not running.

**Comment by tjcelaya** [comment]
Seems to have been intermittent.

**Pull request closed without merging**
