### PR TITLE
Fixes issue with running tests without environment variables set.

### PR DESCRIPTION
**Pull request by dekobon**
@phillipross Please review these changes. This should fix the issue.

### CODE REVIEW

**Comment by phillipross** [comment]
The tests don't pass... but now at least I get an error that the manta key is missing.  I'll include the test output, but it appears that the testng.xml config parameter values are still not making it into the actual initialization of the manta client.

I can see that it's outputting parameters, but they're the wrong values.  keyPath should point to the key in src/test/resources and the fingerprint should not be null.

```
Running TestSuite
[main] DEBUG com.joyent.manta.client.crypto.HttpSigner - initializing HttpSigner with keypath: /Users/phil/.ssh/id_rsa, fingerprint: 7d:dd:93:d0:a8:62:e7:e0:e5:82:34:98:67:23:cd:22, login: prdev
[main] DEBUG com.joyent.manta.client.MantaClient - entering newInstance with url https://us-east.manta.joyent.com, login prdev, keyPath /Users/phil/.ssh/id_rsa, fingerPrint null, timeout 20000
Tests run: 19, Failures: 2, Errors: 0, Skipped: 13, Time elapsed: 1.029 sec <<< FAILURE! - in TestSuite
beforeClass(com.joyent.manta.client.crypto.HttpSignerTest)  Time elapsed: 0.614 sec  <<< FAILURE!
java.lang.ClassCastException: org.bouncycastle.openssl.PEMEncryptedKeyPair cannot be cast to org.bouncycastle.openssl.PEMKeyPair
	at com.joyent.manta.client.crypto.HttpSigner.getKeyPair(HttpSigner.java:148)
	at com.joyent.manta.client.crypto.HttpSigner.<init>(HttpSigner.java:105)
	at com.joyent.manta.client.crypto.HttpSigner.newInstance(HttpSigner.java:63)
	at com.joyent.manta.client.crypto.HttpSignerTest.beforeClass(HttpSignerTest.java:57)

beforeClass(com.joyent.manta.client.MantaClientTest)  Time elapsed: 0.333 sec  <<< FAILURE!
java.lang.IllegalArgumentException: Manta key id must be specified
	at com.joyent.manta.client.MantaClient.<init>(MantaClient.java:179)
	at com.joyent.manta.client.MantaClient.newInstance(MantaClient.java:115)
	at com.joyent.manta.client.MantaClient.newInstance(MantaClient.java:91)
	at com.joyent.manta.client.MantaClient.newInstance(MantaClient.java:68)
	at com.joyent.manta.client.MantaClientTest.beforeClass(MantaClientTest.java:58)

```

**Comment by dekobon** [comment]
Please try after the latest changes.
If that fails, can you give me your test config.

What env vars you have set?
What do you have the following set to:
```
manta.key.fingerprint
manta.test.key.fingerprint
manta.key.private.filename
manta.test.key.private.filename
```
And any other TestNG values that are relevant.

**Comment by phillipross** [comment]
This still fails for me.  I'm actually checking out the repo, switching to the config branch, and then running maven clean test w/ a new local repo and only the MANTA_USER environment variable set and no additional system properties defined.  I'm not making any modifications to any of the source files that are checked out, not even testng.xml.

The commands:
```
git clone https://github.com/joyent/java-manta
cd java-manta/
git checkout config
MANTA_USER=prdev mvn clean test -Dmaven.repo.local=../mvn-repo-local-config
```
and the test output:
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
[main] DEBUG com.joyent.manta.client.crypto.HttpSigner - initializing HttpSigner with keypath: /Users/phil/.ssh/id_rsa, fingerprint: 7d:dd:93:d0:a8:62:e7:e0:e5:82:34:98:67:23:cd:22, login: prdev
[main] DEBUG com.joyent.manta.client.MantaClient - entering newInstance with url https://us-east.manta.joyent.com, login prdev, keyPath /Users/phil/.ssh/id_rsa, fingerPrint null, timeout 20000
Tests run: 19, Failures: 2, Errors: 0, Skipped: 13, Time elapsed: 0.626 sec <<< FAILURE! - in TestSuite
beforeClass(com.joyent.manta.client.crypto.HttpSignerTest)  Time elapsed: 0.502 sec  <<< FAILURE!
java.lang.ClassCastException: org.bouncycastle.openssl.PEMEncryptedKeyPair cannot be cast to org.bouncycastle.openssl.PEMKeyPair
	at com.joyent.manta.client.crypto.HttpSigner.getKeyPair(HttpSigner.java:148)
	at com.joyent.manta.client.crypto.HttpSigner.<init>(HttpSigner.java:105)
	at com.joyent.manta.client.crypto.HttpSigner.newInstance(HttpSigner.java:63)
	at com.joyent.manta.client.crypto.HttpSignerTest.beforeClass(HttpSignerTest.java:60)

beforeClass(com.joyent.manta.client.MantaClientTest)  Time elapsed: 0.037 sec  <<< FAILURE!
java.lang.IllegalArgumentException: Manta key id must be specified
	at com.joyent.manta.client.MantaClient.<init>(MantaClient.java:179)
	at com.joyent.manta.client.MantaClient.newInstance(MantaClient.java:115)
	at com.joyent.manta.client.MantaClient.newInstance(MantaClient.java:91)
	at com.joyent.manta.client.MantaClient.newInstance(MantaClient.java:68)
	at com.joyent.manta.client.MantaClientTest.beforeClass(MantaClientTest.java:62)


Results :

Failed tests: 
  MantaClientTest.beforeClass:62 » IllegalArgument Manta key id must be specifie...
  HttpSignerTest.beforeClass:60 » ClassCast org.bouncycastle.openssl.PEMEncrypte...

Tests run: 19, Failures: 2, Errors: 0, Skipped: 13

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by dekobon** [comment]
If you have only specified MANTA_USER, then it should fail. We need the
fingerprint and the key file path specified. Otherwise, we wouldn't be able
to authenticate.

Basically, you need to specify this information by env vars, sys props or
testng parameters (or some combination thereof).

**Comment by phillipross** [comment]
The information needs to be defined... that is correct.

When the MANTA_KEY_PATH and MANTA_KEY_ID environment variables are not defined, it should fall back on the system properties... and when the system properties are not defined, it should fall back to the ones specified in the testng.xml file.  And when the testng.xml properties are not defined, it should fall back on the defaults.

I think I might have identified the problem.  The order is specified correctly in the test, but the test parameter names are mismatched (see [MantaClientTest line 32](https://github.com/joyent/java-manta/blob/config/src/test/java/com/joyent/manta/client/MantaClientTest.java#L32)) and the testng context is not populated with the values from testng.xml

**Comment by phillipross** [comment]
Also, i think even when the testng confg context is populated with the values from the testng.xml, the system settings config will overwrite the test key path since the system settings config is populated from the default config...which specifies ~/.ssh/id_rsa as the key path.

Maybe the system settings context should not be populated with default values, but only values that are explicitly defined via system properties.

By the same token... environment variable context should not be populated with default values, but only values that are explicitly defined via environment variables.

Additionally, I think system settings config context constructor [contains a line](https://github.com/joyent/java-manta/blob/config/src/main/java/com/joyent/manta/config/SystemSettingsConfigContext.java#L22) which overrides w/ environment variable values as well.  I'm not sure that's supposed to be there.

**Comment by dekobon** [comment]
@phillipross Please review the latest commit to this PR. I've added the tests for precedence, removed the RSA keys entirely and updated the docs.

**Comment by phillipross** [comment]
I tested various permutations of environment variable and system property configurations and those works fine now.  The README is nice and consistent, and the table looks good too.  Good job!

**Pull request merged**
